encoding: utf-8
# Site settings
title: Ratchet Robotics # this *only* affects the <title> with our custom theme
email: team6806@gmail.com
description: >
  A FTC Robotics Team
baseurl: ""
url: "http://ftc-6806.github.io/" # the base hostname & protocol for your site
github_username:  FTC-6806

permalink: "/blog/:categories/:title/"

paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
