# Site settings
title: Ratchet Robotics
email: team6806@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ftc-6806.github.io/" # the base hostname & protocol for your site
github_username:  FTC-6806

# Build settings
markdown: kramdown
